# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Process CI

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/process.yml'
      - 'process/**/*'
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/process.yml'
      - 'process/**/*'

defaults:
  run:
    working-directory: process

jobs:
  process-brussels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run update
        run: composer run update-data -- --city=belgium/brussels

  phpcs:
    name: PHP_CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: composer install --prefer-dist --no-progress
      - name: Configure PHPCS
        run: ./vendor/squizlabs/php_codesniffer/bin/phpcs --config-set ignore_warnings_on_exit 1
      - run: composer run-script cs-check

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: composer install --prefer-dist --no-progress
      - run: composer run-script analyze